### ISSUE TITLE
Add US-RI-RIPTA as new network

### ISSUE THREAD

**Issue by kevin-brown** [osm-ToniE/ptna-networks#103]
Long network/operator name: Rhode Island Public Transit Authority
Short network/operator name: RIPTA
Official website: https://ripta.com
Transitland: https://www.transit.land/operators/o-drm-rhodeislandpublictransitauthority
GTFS feed: https://ripta.com/RIPTA-GTFS.zip
Search area: State of Rhode Island

**Comment by osm-ToniE** [comment]
Done, kindly see:
- [PTNA: news for Public Transport Network Analysis #100](https://community.openstreetmap.org/t/ptna-news-for-public-transport-network-analysis/8383/100)
- [Proposal - RIPTA Import](https://community.openstreetmap.org/t/proposal-ripta-import/107231)
