### ISSUE TITLE
Please add NYC's MTA transit network.

### ISSUE THREAD

**Issue by mxxcon** [osm-ToniE/ptna-networks#90]
Please add New York City's MTA transit network of busses, subways, and ferry if possible.
The official website is https://new.mta.info/
GTFS feeds are available at from https://www.transit.land/operators/o-dr5r-nyct and https://www.transit.land/operators/o-dr5r7-nycdot

**Comment by osm-ToniE** [comment]
Thanks.

I have a question regarding the GTFS data
- Staten Island buses - f-dr5r-mtanyctbusstatenisland
- Manhattan buses - f-dr5r-mtanyctbusmanhattan
- Queens buses - f-dr5x-mtanyctbusqueens
- Bronx buses - f-dr72-mtanyctbusbronx
- Brooklyn buses - f-dr5r-mtanyctbusbrooklyn

In addition there are the also the following
- f-dr5r-mtabc - ???
- f-dr5r-mtanewyorkcitytransit - ???
- f-dr5r-nyctsubway - all subway lines, not operated by MTA?
- f-dr5r7-nycdotsiferry - Staten Island Ferry, not operated by MTA?
What do the first two stand for?
Are that last two not part of the MTA network?

Thanks

**Comment by osm-ToniE** [comment]
Another Question regarding the search area

- NCY - OK
- Long Island - ?
- Connecticut - ?
- Southeastern New York State - which counties ?

> The Metropolitan Transportation Authority is North America's largest transportation network, serving a population of 15.3 million people across a 5,000-square-mile travel area surrounding **New York City, Long Island, southeastern New York State, and Connecticut**.

**Comment by osm-ToniE** [comment]
Which 'network' values are valid?

- Metropolitan Transportation Authority
- MTA

aren't used at all.

What I see also as 'network' https://ptna.openstreetmap.de/results/US/NY/US-NY-MTA-Analysis.html#networkdetails

- MTA New York City Bus
- NY Waterway
- NYC Subway
- NYC Transit
- Staten Island Ferry
- Staten Island Railway
They are not considered as relevant at the moment, I can add them though

**Comment by mxxcon** [comment]
>     * f-dr5r-mtabc - ???

It looks like they are also city bus routes.
If you look at https://www.transit.land/operators/o-dr5r-nyct#routes you'll see that they are listed as "_MTA Bus Company_" instead of "_MTA New York City Transit_" like other routes.

Looking at wikipedia article for one of the lines there https://en.wikipedia.org/wiki/Q72_(New_York_City_bus) it says:
> It is city-operated under the [MTA Bus Company](https://en.wikipedia.org/wiki/MTA_Bus_Company) brand of [MTA Regional Bus Operations](https://en.wikipedia.org/wiki/MTA_Regional_Bus_Operations).

I guess it's quirk of when MTA acquired/merged with some of the other smaller local bus operators.

>Regional Bus Operations is currently only used in official documentation, and not publicly as a brand. The current public brands are listed below:
>    **MTA New York City Bus** – most routes within the City of New York, operated by the [New York City Transit Authority](https://en.wikipedia.org/wiki/New_York_City_Transit_Authority) (NYCT) and subsidiary Manhattan and Bronx Surface Transit Operating Authority (MaBSTOA).
>    **MTA Bus** – service previously administered by the [New York City Department of Transportation](https://en.wikipedia.org/wiki/New_York_City_Department_of_Transportation) and operated by seven companies at the time of the takeover, mostly concentrated in Queens, with some routes in the Bronx and Brooklyn, and most express service from Brooklyn, Queens and the Bronx to Manhattan. The seven former companies were, [Command Bus Company](https://en.wikipedia.org/wiki/Varsity_Bus_Company), Inc.; [Green Bus Lines](https://en.wikipedia.org/wiki/Green_Bus_Lines), Inc.; [Jamaica Buses](https://en.wikipedia.org/wiki/Jamaica_Buses), Inc., [Liberty Lines Express](https://en.wikipedia.org/wiki/Liberty_Lines_Express), Inc.; [New York Bus Service](https://en.wikipedia.org/wiki/New_York_Bus_Service), Inc.; [Queens Surface](https://en.wikipedia.org/wiki/Queens_Surface) Corp.; and [Triboro Coach](https://en.wikipedia.org/wiki/Triboro_Coach) Corp.

For customers all these are just regular city buses with the usual branding, look and fare system.

------

> 
>     * f-dr5r-mtanewyorkcitytransit - ???

transit.land site shows no routes associated with this, but when I downloaded http://web.mta.info/developers/files/google_transit_supplemented.zip that's linked there, I do see `routes.txt` file which looks to contain all the same NYC's subway lines.
I'm not familiar with GTFS' nuances to understand the difference between this and `f-dr5r-nyctsubway` or why there are 2 of them.

>     * f-dr5r-nyctsubway - all subway lines, not operated by MTA?

They are operated by MTA.

>     * f-dr5r7-nycdotsiferry - Staten Island Ferry, not operated by MTA?

NYC DOT, not MTA, operates the Staten Island Ferry, providing free service between Staten Island and Lower Manhattan every day of the week, year-round.
https://www.nyc.gov/html/dot/html/ferrybus/staten-island-ferry.shtml

>       Are that last two not part of the MTA network?

SI Ferry is not really part of "MTA" network.
There are also other ferry routes around NYC, but they are also not operated by MTA. Some might be using MTA's MetroCard and OMNI fare payment system, but I'm not sure, I've never taken them.

**Comment by osm-ToniE** [comment]
I suggest keeping the search area to NYC and see what might be missing after having sorted all the stuff.
I want the search area as tiny as possible. PTNA will find all relations which have at least a one node (platform, stop, node of way) in the search area - incl. their route_masters and brother/sister relations in the route_masters.
That should match for the time being.

I see 'network' = 'LIRR' in the analysis report, so the current search might find many of the extra lines

I will extend the list of accepted 'network' values by
- MTA New York City Bus
- NY Waterway
- NYC Subway
- NYC Transit
- Staten Island Ferry
- Staten Island Railway
- LIRR

and we'll see the outcome.

**Comment by osm-ToniE** [comment]
Is it OK for GTFS to start with
* US-NY-MTA-Subway - f-dr5r-nyctsubway
* US-NY-MTA-Bronx-Bus - f-dr72-mtanyctbusbronx
* US-NY-MTA-Brooklyn-Bus - f-dr5r-mtanyctbusbrooklyn
* US-NY-MTA-Manhattan-Bus - f-dr5r-mtanyctbusmanhattan
* US-NY-MTA-Queens-Bus - f-dr5x-mtanyctbusqueens
* US-NY-MTA-Staten-Island-Bus - f-dr5r-mtanyctbusstatenisland
* US-NY-MTA-Bus-Company  - f-dr5r-mtabc

**Comment by mxxcon** [comment]
> Is it OK for GTFS to start with

why wouldn't it be?

**Comment by osm-ToniE** [comment]
I wasn't clear on how to name them.

- MTA NYCT offers services in the 5 boroughs configured with 5 GTFS feeds
- MTA Bus Company offers services NYC wide with a single GTFS feed

Should that be reflected in the name of the feed?

BTW: f-dr5r-nyctsubway and f-dr5r-mtanewyorkcitytransit are identical, so we're fine with the 7 GTFS feeds above (I hope)

**Comment by mxxcon** [comment]
> * MTA NYCT offers services in the 5 boroughs configured with 5 GTFS feeds
> * MTA Bus Company offers services NYC wide with a single GTFS feed

To the riders it all looks like the same company and service, so I don't think we should bother trying to document their internal corporate structure in OSM tags. A common system-wide name is fine.

Regarding subway feeds, `f-dr5r-mtanewyorkcitytransit` seems to be much larger, but I don't know if the differences are something that's relevant for your site.

**Comment by osm-ToniE** [comment]
Released

**Comment by osm-ToniE** [comment]
> To the riders it all looks like the same company and service, so I don't think we should bother trying to document their internal corporate structure in OSM tags. A common system-wide name is fine.

Yep, except if this makes a difference in 'operator' values

> Regarding subway feeds, f-dr5r-mtanewyorkcitytransit seems to be much larger, but I don't know if the differences are something that's relevant for your site.

Oops, I did check routes.txt and trips.txt and they are identical. I did not check shape.txt though. Would be beneficial to present the shapes also.

**Comment by mxxcon** [comment]
I've been thinking about the value of `network=` tag and it seems like it is duplicating the values of `operator=` tags. Shouldn't it be different?
For example looking at Wikidata [article for the subway network](https://www.wikidata.org/wiki/Q7733), and the linked Wikipedia article, they both refer to it as "_New York City Subway_". So maybe that's what this tag for subway should be?

Similarly, for the buses shouldn't it be different from the value of `operator=` tag? Maybe it makes sense to use "_MTA New York City Bus_"?

I'm not quiet clear on all the semantics and implications if these tags change...

And I'm thinking that a similar change needs to happen to https://github.com/osmlab/name-suggestion-index/blob/main/data/transit/route/bus.json#L10440 and https://github.com/osmlab/name-suggestion-index/blob/main/data/transit/route/subway.json#L332, 
and maybe https://github.com/osmlab/name-suggestion-index/blob/main/data/transit/route/train.json#L919 and https://github.com/osmlab/name-suggestion-index/blob/main/data/transit/route/train.json#L1067 so that at a later point these changes won't get clobbered by iD/Rapid/other editor that uses NSI. 🤔

**Comment by osm-ToniE** [comment]
> I'm not quiet clear on all the semantics and implications if these tags change...

Yeah, right! There is no clear understanding OSM-world-wide either.

I see 'network' as the authority which organizes the PT in the area, is partly funded/subsidized by government (on lower level: county) to have reasonable fares, defines tariff zones, (transfer) rules, ... and - now coming to the 'operator' section - publishes "public invitation to bid" for operating a specific bus/subway/... route for the next 3-5 years with a requested SLA.

'operator' can participate in this bid and hope to get the contract, then buy buses/..., hire drivers, ... hoping to operator the route with a financial revenue.

That's simply spoken; how it works here in Munich, DE and will definitely not apply world-wide.

So, f.m.p.o.v. it's a task for the local mappers to define the semantics.  A possible mapping is "agency" of GTFS to 'operator' in OSM.

**Comment by mxxcon** [comment]
I noticed an issue with some of the subway lines.
In section [3.1 Subway/Underground (subway)](https://ptna.openstreetmap.de/results/US/NY/US-NY-MTA-Analysis.html#A3.1) you have `<6>`, `<7>`, `<F>` routes and in [2.3.1 NYC Subway](https://ptna.openstreetmap.de/results/US/NY/US-NY-MTA-Analysis.html#A2.3.1) you have empty entries for 6X, 7X, FX lines.

They are the same thing. The trains have "diamond" symbol on their displays and MTA calls them "express" lines.
You can see that if you download PDF schedules of these lines from https://new.mta.info/schedules
For example 2nd to the last page of the 7 line shows:
![image](https://github.com/osm-ToniE/ptna-networks/assets/847140/5b72aee1-d9e3-40c3-bc27-d75a3aec75aa)
Wikipedia article also mentions these diamond designations https://en.wikipedia.org/wiki/New_York_City_Subway_nomenclature#Diamond_services

I'm guessing in GTFS feed MTA uses 6X, 7X, FX because <> characters are not allowed or somehow else cause problems.
It would be great if you could associate these lines to each other. 👍

**Comment by osm-ToniE** [comment]
I've changed that in the [CSV input data for PTNA](https://wiki.openstreetmap.org/wiki/New_York_City/MTA/Analysis/MTA-Routes).
This data is intended to be maintained by local mappers.

Neither GTFS nor OSM have a way expressing the diamond symbol, nor do they have a way expressing complex colour schemes like the (quite simple) one for the subway U8 here
![grafik](https://github.com/osm-ToniE/ptna-networks/assets/26119392/864dd0a0-6250-47ac-9815-8cf30f5ee0b7)
