### ISSUE TITLE
Add additional US-MA networks that roll up to the MADOT

### ISSUE THREAD

**Issue by kevin-brown** [osm-ToniE/ptna-networks#93]
GATRA
* Long network/operator name: Greater Attleboro Taunton Regional Transit Authority
* Short network/operator name: GATRA
* Official website: https://www.gatra.org/
* Transitland: https://www.transit.land/operators/o-drm-thegreaterattleborotauntonregionaltransitauthority

MWRTA
* Long: MetroWest Regional Transit Authority
* Short: MWRTA
* Official website: https://www.mwrta.com/
* Transitland: https://www.transit.land/operators/o-drt0-metrowestregionaltransitauthority

LRTA
* Long: Lowell Regional Transit Authority
* Short: LRTA
* Official website: https://www.lrta.com
* Transitland: https://www.transit.land/operators/o-drt6-lowellregionaltransitauthority

PVTA
* Long: Pioneer Valley Transit Authority
* Short: PVTA
* Official website: https://www.pvta.com
* Transitland: https://www.transit.land/operators/o-drk-pvta/

Associations sourced from https://www.mass.gov/lists/mbta-and-transit-data-for-developers, I will likely request to add more in the future.

**Comment by osm-ToniE** [comment]
I've prepared the PTNA stuff so far analysing the OSM data.

Kindly let me know whether the "search areas" for the Overpass-API queries (as shown in the second column on the [US page](https://ptna.openstreetmap.de/results/US/index.php)) fit or need to be extended to include more counties.

Also, let me know whether the locations in the OSM Wiki are OK for you (see last column in the table) to store the CSV list.

**Comment by kevin-brown** [comment]
> I've prepared the PTNA stuff so far analysing the OSM data.

Thanks for the quick turnaround!

> Kindly let me know whether the "search areas" for the Overpass-API queries (as shown in the second column on the [US page](https://ptna.openstreetmap.de/results/US/index.php)) fit or need to be extended to include more counties.

All look good except for the PVTA I believe, which needs Hampden County added to it (in addition to the existing Hampshire County).

> Also, let me know whether the locations in the OSM Wiki are OK for you (see last column in the table) to store the CSV list.

Those locations look good in the OSM Wiki.

**Comment by osm-ToniE** [comment]
Thanks, I added Hampden County and that nearly doubled the number of routes.

For the GTFS integration, I'll find sometime next week.
